site_name: NeuroScript
site_url: https://aprice2704.github.io/neuroscript/
repo_url: https://github.com/aprice2704/neuroscript

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Road Map: RoadMap.md
  - Overview:
      - Why NeuroScript: front/why-ns.md
      - Architecture: front/architecture.md
      - Core Concepts: front/concepts.md
      - Installation: front/installation.md
      - FAQ: front/faq.md
      - Contributing: front/contributing.md
  - Specifications:
      - Quick Spec: script_spec.md
      - Formal Spec: "formal script spec.md"
      - Metadata: metadata.md
      - NeuroData & Composite: neurodata_and_composite_file_spec.md
      - LLM Agent Facilities: llm_agent_facilities.md
      - Restricted Mode: restricted_mode.md
      - Spec Structure Guide: specification_structure.md
  - NeuroData Types:
      - Checklist: NeuroData/checklist.md
      - Cryptographic: NeuroData/cryptographic.md
      - Decision Table: NeuroData/decision_table.md
      - Enum: NeuroData/enum.md
      - Form: NeuroData/form.md
      - Geometry: NeuroData/geometry.md
      - Graph: NeuroData/graph.md
      - List: NeuroData/list.md
      - Map Literal: NeuroData/map_literal.md
      - Map Schema: NeuroData/map_schema.md
      - Patch: NeuroData/patch.md
      - References: NeuroData/references.md
      - Symbolic Math: NeuroData/symbolic_math.md
      - Table: NeuroData/table.md
      - Templates: NeuroData/templates.md
      - Tree: NeuroData/tree.md
  - Tools:
      - Index: ns/tools/index.md
      - delete_api_file: ns/tools/delete_api_file.md
      - fs_deletefile: ns/tools/fs_deletefile.md
      - fs_filehash: ns/tools/fs_filehash.md
      - fs_linecountfile: ns/tools/fs_linecountfile.md
      - fs_mkdir: ns/tools/fs_mkdir.md
      - fs_movefile: ns/tools/fs_movefile.md
      - fs_readfile: ns/tools/fs_readfile.md
      - fs_sanitizefilename: ns/tools/fs_sanitizefilename.md
      - fs_walkdir: ns/tools/fs_walkdir.md
      - fs_writefile: ns/tools/fs_writefile.md
      - git_add: ns/tools/git_add.md
      - git_checkout: ns/tools/git_checkout.md
      - git_commit: ns/tools/git_commit.md
      - git_diff: ns/tools/git_diff.md
      - git_gitstatus: ns/tools/git_gitstatus.md
      - git_merge: ns/tools/git_merge.md
      - git_newbranch: ns/tools/git_newbranch.md
      - git_pull: ns/tools/git_pull.md
      - git_push: ns/tools/git_push.md
      - git_rm: ns/tools/git_rm.md
      - git_status: ns/tools/git_status.md
      - go_build: ns/tools/go_build.md
      - go_update_imports_for_moved_package: ns/tools/go_update_imports_for_moved_package.md
      - list_api_files: ns/tools/list_api_files.md
      - maths: ns/tools/maths.md
      - move_file: ns/tools/move_file.md
      - query_table: ns/tools/query_table.md
      - strings: ns/tools/strings.md
      - sync_files: ns/tools/sync_files.md
      - tool_spec_structure: ns/tools/tool_spec_structure.md
      - upload_file: ns/tools/upload_file.md
      - vector_searchskills: ns/tools/vector_searchskills.md
      - vector_update: ns/tools/vector_update.md
  - Status & Build:
      - Build Guide: build.md
      - Completed Checklist: completed.md
      - Release Checklist: release_checklist.ndcl.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite

plugins:
  - search
