// NeuroScript Version: 0.5.2
// File version: 1
// Purpose: Defines the core types.Diagnostic type for the entire system.
// filename: pkg/types/diag.go
// nlines: 23
// risk_rating: LOW

package types

// Severity indicates the seriousness of a diagnostic message.
type Severity int

const (
	SeverityError   Severity = 1
	SeverityWarning Severity = 2
	SeverityInfo    Severity = 3
	SeverityHint    Severity = 4
)

// types.Diag represents a single diagnostic message, such as a linter error or
// a compiler warning, generated by an analysis pass or other system component.
type Diag struct {
	Severity Severity
	Position *Position
	Message  string
	Source   string // The name of the component that generated the diagnostic (e.g., "typecheck")
}
