// Code generated by goyacc -v y.output -o neuroscript.y.go -p yy neuroscript.y. DO NOT EDIT.

//line neuroscript.y:4
package core // Must match package in lexer and ast
import __yyfmt__ "fmt"

//line neuroscript.y:4

import (
	"fmt"
	"strings"
)

// var parsedResult []Procedure // Removed global

func newStep(typ string, target string, cond string, value interface{}, args []string) Step {
	return Step{Type: typ, Target: target, Cond: cond, Value: value, Args: args}
}

var currentParsedDocstring string

//line neuroscript.y:21
type yySymType struct {
	yys        int
	str        string
	step       Step
	steps      []Step
	proc       Procedure
	procs      []Procedure // Type for lists of procedures
	params     []string
	args       []string // For CALL arguments
	expr       string
	exprs      []string // For expression lists (arguments, list literals)
	mapEntries []string // For map entries string representations
}

const IDENTIFIER = 57346
const STRING_LIT = 57347
const DOC_COMMENT_CONTENT = 57348
const KW_DEFINE = 57349
const KW_PROCEDURE = 57350
const KW_COMMENT = 57351
const KW_END = 57352
const KW_SET = 57353
const KW_CALL = 57354
const KW_RETURN = 57355
const KW_IF = 57356
const KW_THEN = 57357
const KW_WHILE = 57358
const KW_DO = 57359
const KW_FOR = 57360
const KW_EACH = 57361
const KW_IN = 57362
const KW_TOOL = 57363
const KW_LLM = 57364
const KW_ELSE = 57365
const ASSIGN = 57366
const PLUS = 57367
const LPAREN = 57368
const RPAREN = 57369
const COMMA = 57370
const LBRACK = 57371
const RBRACK = 57372
const LBRACE = 57373
const RBRACE = 57374
const COLON = 57375
const DOT = 57376
const PLACEHOLDER_START = 57377
const PLACEHOLDER_END = 57378
const KW_LAST_CALL_RESULT = 57379
const EQ = 57380
const NEQ = 57381
const NEWLINE = 57382
const INVALID = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING_LIT",
	"DOC_COMMENT_CONTENT",
	"KW_DEFINE",
	"KW_PROCEDURE",
	"KW_COMMENT",
	"KW_END",
	"KW_SET",
	"KW_CALL",
	"KW_RETURN",
	"KW_IF",
	"KW_THEN",
	"KW_WHILE",
	"KW_DO",
	"KW_FOR",
	"KW_EACH",
	"KW_IN",
	"KW_TOOL",
	"KW_LLM",
	"KW_ELSE",
	"ASSIGN",
	"PLUS",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"LBRACK",
	"RBRACK",
	"LBRACE",
	"RBRACE",
	"COLON",
	"DOT",
	"PLACEHOLDER_START",
	"PLACEHOLDER_END",
	"KW_LAST_CALL_RESULT",
	"EQ",
	"NEQ",
	"NEWLINE",
	"INVALID",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line neuroscript.y:143
/* Go code section */

// yyError function remains the same
func yyError(s string) {
	fmt.Printf("Syntax Error: %s\n", s)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 130

var yyAct = [...]int8{
	18, 68, 73, 58, 45, 105, 31, 32, 33, 34,
	61, 35, 38, 36, 101, 31, 32, 33, 34, 65,
	35, 14, 36, 100, 31, 32, 33, 34, 5, 35,
	64, 36, 76, 77, 85, 22, 57, 44, 90, 20,
	31, 32, 33, 34, 22, 35, 88, 36, 86, 62,
	89, 87, 13, 22, 66, 65, 103, 84, 96, 70,
	12, 4, 48, 51, 65, 81, 80, 70, 63, 22,
	83, 8, 59, 65, 95, 60, 91, 78, 75, 94,
	92, 93, 37, 41, 50, 17, 6, 55, 19, 56,
	74, 97, 98, 54, 99, 49, 82, 79, 67, 102,
	42, 43, 39, 15, 104, 11, 7, 16, 72, 71,
	69, 53, 52, 47, 46, 40, 27, 26, 25, 30,
	29, 28, 24, 23, 21, 10, 9, 3, 2, 1,
}

var yyPact = [...]int16{
	-1000, -1000, 21, -1000, -1000, 78, 102, 45, 101, 33,
	24, -1000, -19, 99, 76, -1000, -1000, 82, 29, 72,
	-28, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 98, 79, 58, 58, 58, 56, -30, -1000, 25,
	42, -1000, -4, -1000, 48, -1000, -1000, -1000, -1000, -1000,
	58, -1000, -1000, -1000, 94, 58, 85, 63, -6, 60,
	93, -1000, 58, 58, 92, 58, 30, -2, 18, 23,
	48, 14, 22, -1000, 5, -1000, 58, 58, -1000, 54,
	48, 31, -1000, -1000, -1000, -1000, -1000, 58, -1000, 85,
	58, 13, 48, 48, 4, 58, -1000, 48, -1000, 48,
	-1000, -1000, 39, -1000, -5, -1000,
}

var yyPgo = [...]uint8{
	0, 129, 128, 127, 126, 125, 0, 124, 123, 122,
	121, 120, 119, 118, 117, 116, 115, 3, 4, 114,
	113, 36, 112, 111, 2, 1, 110, 109, 108, 107,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 4, 4, 5, 5,
	29, 6, 6, 6, 7, 7, 8, 8, 8, 9,
	9, 9, 13, 14, 15, 15, 10, 11, 12, 16,
	16, 16, 21, 21, 21, 17, 17, 18, 18, 18,
	18, 18, 20, 19, 19, 19, 22, 23, 25, 25,
	26, 26, 27, 27, 28, 28, 24,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 2, 11, 0, 1, 1, 3,
	4, 0, 2, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 5, 1, 2, 5, 5, 8, 1,
	3, 1, 1, 3, 3, 1, 3, 1, 1, 1,
	1, 3, 3, 1, 1, 1, 3, 3, 0, 1,
	1, 3, 0, 1, 1, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 40, 7, 8, 4, 26, -4,
	-5, 4, 27, 28, 40, 4, -29, 9, -6, 6,
	10, -7, 40, -8, -9, -13, -14, -15, -10, -11,
	-12, 11, 12, 13, 14, 16, 18, 10, 40, 4,
	-16, 4, 21, 22, -17, -18, -19, -20, 4, 37,
	26, 5, -22, -23, 35, 29, 31, -21, -17, -21,
	19, 40, 24, 26, 34, 25, -17, 4, -25, -26,
	-17, -27, -28, -24, 5, 15, 38, 39, 17, 4,
	-17, -25, 4, -18, 27, 36, 30, 28, 32, 28,
	33, -6, -17, -17, -6, 20, 27, -17, -24, -17,
	10, 10, -17, 17, -6, 10,
}

var yyDef = [...]int8{
	2, -2, 1, 3, 4, 0, 0, 0, 6, 0,
	7, 8, 0, 0, 0, 9, 11, 0, 0, 0,
	0, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 0, 0, 24, 0, 0, 0, 0, 5, 0,
	0, 29, 0, 31, 25, 35, 37, 38, 39, 40,
	0, 43, 44, 45, 0, 48, 52, 0, 32, 0,
	0, 10, 0, 48, 0, 0, 0, 0, 0, 49,
	50, 0, 53, 54, 0, 11, 0, 0, 11, 0,
	22, 0, 30, 36, 41, 42, 46, 0, 47, 0,
	0, 0, 33, 34, 0, 0, 23, 51, 55, 56,
	26, 27, 0, 11, 0, 28,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:74
		{
			if l, ok := yylex.(*lexer); ok {
				l.SetResult(yyDollar[1].procs)
			} else {
				fmt.Println("Error: Could not access lexer object to set result.")
			}
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:83
		{
			yyVAL.procs = []Procedure{}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:84
		{
			yyVAL.procs = append(yyDollar[1].procs, yyDollar[2].proc)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:85
		{
			yyVAL.procs = yyDollar[1].procs
		}
	case 5:
		yyDollar = yyS[yypt-11 : yypt+1]
//line neuroscript.y:90
		{
			var proc Procedure
			proc.Name = yyDollar[3].str
			proc.Params = yyDollar[5].params
			proc.Steps = yyDollar[9].steps
			yyVAL.proc = proc
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:97
		{
			yyVAL.params = []string{}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:97
		{
			yyVAL.params = yyDollar[1].params
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:98
		{
			yyVAL.params = []string{yyDollar[1].str}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:98
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].str)
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line neuroscript.y:100
		{
			yyVAL.str = yyDollar[2].str
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:102
		{
			yyVAL.steps = []Step{}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:103
		{
			if yyDollar[2].step.Type != "" {
				yyVAL.steps = append(yyDollar[1].steps, yyDollar[2].step)
			} else {
				yyVAL.steps = yyDollar[1].steps
			}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:104
		{
			yyVAL.steps = yyDollar[1].steps
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:108
		{
			yyVAL.step = yyDollar[1].step
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:109
		{
			yyVAL.step = yyDollar[1].step
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line neuroscript.y:119
		{
			yyVAL.step = newStep("SET", yyDollar[2].str, "", yyDollar[4].str, nil)
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
//line neuroscript.y:120
		{
			yyVAL.step = newStep("CALL", yyDollar[2].str, "", nil, yyDollar[4].exprs)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:121
		{
			yyVAL.step = newStep("RETURN", "", "", "", nil)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:121
		{
			yyVAL.step = newStep("RETURN", "", "", yyDollar[2].str, nil)
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line neuroscript.y:124
		{
			yyVAL.step = newStep("IF", "", yyDollar[2].str, yyDollar[4].steps, nil)
		}
	case 27:
		yyDollar = yyS[yypt-5 : yypt+1]
//line neuroscript.y:125
		{
			yyVAL.step = newStep("WHILE", "", yyDollar[2].str, yyDollar[4].steps, nil)
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
//line neuroscript.y:126
		{
			yyVAL.step = newStep("FOR", yyDollar[3].str, yyDollar[5].str, yyDollar[7].steps, nil)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:129
		{
			yyVAL.str = yyDollar[1].str
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:129
		{
			yyVAL.str = "TOOL." + yyDollar[3].str
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:129
		{
			yyVAL.str = "LLM"
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:130
		{
			yyVAL.str = yyDollar[1].str
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:130
		{
			yyVAL.str = yyDollar[1].str + "==" + yyDollar[3].str
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:130
		{
			yyVAL.str = yyDollar[1].str + "!=" + yyDollar[3].str
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:131
		{
			yyVAL.str = yyDollar[1].str
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:131
		{
			yyVAL.str = yyDollar[1].str + " + " + yyDollar[3].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:132
		{
			yyVAL.str = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:132
		{
			yyVAL.str = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:132
		{
			yyVAL.str = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:132
		{
			yyVAL.str = "__last_call_result"
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:132
		{
			yyVAL.str = "(" + yyDollar[2].str + ")"
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:133
		{
			yyVAL.str = "{{" + yyDollar[2].str + "}}"
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:134
		{
			yyVAL.str = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:134
		{
			yyVAL.str = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:134
		{
			yyVAL.str = yyDollar[1].str
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:135
		{
			yyVAL.str = "[" + strings.Join(yyDollar[2].exprs, ", ") + "]"
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:136
		{
			yyVAL.str = "{" + strings.Join(yyDollar[2].mapEntries, ", ") + "}"
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:137
		{
			yyVAL.exprs = []string{}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:137
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:138
		{
			yyVAL.exprs = []string{yyDollar[1].str}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:138
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].str)
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:139
		{
			yyVAL.mapEntries = []string{}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:139
		{
			yyVAL.mapEntries = yyDollar[1].mapEntries
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:140
		{
			yyVAL.mapEntries = []string{yyDollar[1].str}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:140
		{
			yyVAL.mapEntries = append(yyDollar[1].mapEntries, yyDollar[3].str)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:141
		{
			yyVAL.str = yyDollar[1].str + ":" + yyDollar[3].str
		}
	}
	goto yystack /* stack new state and value */
}
