// Code generated by goyacc -o neuroscript.y.go -p yy neuroscript.y. DO NOT EDIT.

//line neuroscript.y:4
package core // Must match package in lexer and ast
import __yyfmt__ "fmt"

//line neuroscript.y:4

import (
	"fmt"
	"strings"
)

var parsedResult []Procedure

func newStep(typ string, target string, cond string, value interface{}, args []string) Step {
	// Assuming Step struct is defined in this package (ast.go)
	return Step{Type: typ, Target: target, Cond: cond, Value: value, Args: args}
}

// Global variable to hold the parsed docstring content temporarily
// TODO: Improve this mechanism, maybe pass lexer state to actions
var currentParsedDocstring string

//line neuroscript.y:23
type yySymType struct {
	yys        int
	str        string
	step       Step
	steps      []Step
	proc       Procedure
	procs      []Procedure
	params     []string
	args       []string // For CALL arguments
	expr       string
	exprs      []string // For expression lists (arguments, list literals)
	mapEntries []string // For map entries string representations
}

const IDENTIFIER = 57346
const STRING_LIT = 57347
const DOC_COMMENT_CONTENT = 57348
const KW_DEFINE = 57349
const KW_PROCEDURE = 57350
const KW_COMMENT = 57351
const KW_END = 57352
const KW_SET = 57353
const KW_CALL = 57354
const KW_RETURN = 57355
const KW_IF = 57356
const KW_THEN = 57357
const KW_WHILE = 57358
const KW_DO = 57359
const KW_FOR = 57360
const KW_EACH = 57361
const KW_IN = 57362
const KW_TOOL = 57363
const KW_LLM = 57364
const KW_ELSE = 57365
const ASSIGN = 57366
const PLUS = 57367
const LPAREN = 57368
const RPAREN = 57369
const COMMA = 57370
const LBRACK = 57371
const RBRACK = 57372
const LBRACE = 57373
const RBRACE = 57374
const COLON = 57375
const DOT = 57376
const PLACEHOLDER_START = 57377
const PLACEHOLDER_END = 57378
const KW_LAST_CALL_RESULT = 57379
const EQ = 57380
const NEQ = 57381
const NEWLINE = 57382
const INVALID = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING_LIT",
	"DOC_COMMENT_CONTENT",
	"KW_DEFINE",
	"KW_PROCEDURE",
	"KW_COMMENT",
	"KW_END",
	"KW_SET",
	"KW_CALL",
	"KW_RETURN",
	"KW_IF",
	"KW_THEN",
	"KW_WHILE",
	"KW_DO",
	"KW_FOR",
	"KW_EACH",
	"KW_IN",
	"KW_TOOL",
	"KW_LLM",
	"KW_ELSE",
	"ASSIGN",
	"PLUS",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"LBRACK",
	"RBRACK",
	"LBRACE",
	"RBRACE",
	"COLON",
	"DOT",
	"PLACEHOLDER_START",
	"PLACEHOLDER_END",
	"KW_LAST_CALL_RESULT",
	"EQ",
	"NEQ",
	"NEWLINE",
	"INVALID",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line neuroscript.y:131
/* Go code section */

// Removed duplicate yyLexer interface def
// Removed duplicate yyParse func def

// yyError is the error reporting function required by goyacc
func yyError(s string) {
	fmt.Printf("Syntax Error: %s\n", s)
}

// Add SetResult to lexer struct if results are stored there
// func (l *lexer) SetResult(res []Procedure) { l.result = res }
//
//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 133

var yyAct = [...]int8{
	17, 72, 57, 44, 67, 4, 108, 30, 31, 32,
	33, 106, 34, 94, 35, 104, 30, 31, 32, 33,
	64, 34, 91, 35, 103, 30, 31, 32, 33, 79,
	34, 37, 35, 75, 76, 43, 21, 18, 3, 13,
	19, 30, 31, 32, 33, 21, 34, 85, 35, 47,
	50, 56, 65, 63, 21, 90, 88, 69, 86, 89,
	87, 64, 12, 84, 80, 69, 96, 81, 83, 11,
	21, 49, 62, 105, 54, 7, 55, 64, 92, 93,
	53, 64, 48, 61, 40, 95, 58, 59, 77, 74,
	97, 98, 100, 99, 60, 101, 16, 5, 102, 36,
	73, 41, 42, 82, 78, 66, 38, 107, 14, 10,
	6, 15, 71, 70, 68, 52, 51, 46, 45, 39,
	26, 25, 24, 29, 28, 27, 23, 22, 20, 9,
	8, 2, 1,
}

var yyPact = [...]int16{
	-1000, -2, -1000, -1000, 89, 106, 49, 105, 42, 34,
	-1000, -1, 104, 87, -1000, -1000, -3, 30, 93, -9,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	102, 80, 45, 45, 45, 68, 84, -1000, 59, 46,
	-1000, 19, -1000, 52, -1000, -1000, -1000, -1000, -1000, 45,
	-1000, -1000, -1000, 101, 45, 95, 74, -5, 71, 100,
	-11, 45, 45, 99, 45, 36, 11, 28, 32, 52,
	24, 31, -1000, 22, -18, 45, 45, -27, 65, -1000,
	52, 39, -1000, -1000, -1000, -1000, -1000, 45, -1000, 95,
	45, -1000, 52, 52, -1000, 45, -1000, 52, -1000, 52,
	14, 5, 56, -1000, -1000, -29, -1000, -4, -1000,
}

var yyPgo = [...]uint8{
	0, 132, 131, 130, 129, 0, 128, 127, 126, 125,
	124, 123, 122, 121, 120, 119, 2, 3, 118, 117,
	51, 116, 115, 1, 4, 114, 113, 112, 111,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 3, 3, 4, 4, 28,
	5, 5, 5, 6, 6, 7, 7, 7, 8, 8,
	8, 12, 13, 14, 14, 9, 10, 11, 15, 15,
	15, 20, 20, 20, 16, 16, 17, 17, 17, 17,
	17, 19, 18, 18, 18, 21, 22, 24, 24, 25,
	25, 26, 26, 27, 27, 23,
}

var yyR2 = [...]int8{
	0, 0, 2, 2, 11, 0, 1, 1, 3, 5,
	0, 2, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 4, 5, 1, 2, 6, 6, 9, 1, 3,
	1, 1, 3, 3, 1, 3, 1, 1, 1, 1,
	3, 3, 1, 1, 1, 3, 3, 0, 1, 1,
	3, 0, 1, 1, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, 40, 7, 8, 4, 26, -3, -4,
	4, 27, 28, 40, 4, -28, 9, -5, 40, 10,
	-6, 40, -7, -8, -12, -13, -14, -9, -10, -11,
	11, 12, 13, 14, 16, 18, 6, 40, 4, -15,
	4, 21, 22, -16, -17, -18, -19, 4, 37, 26,
	5, -21, -22, 35, 29, 31, -20, -16, -20, 19,
	10, 24, 26, 34, 25, -16, 4, -24, -25, -16,
	-26, -27, -23, 5, 15, 38, 39, 17, 4, 40,
	-16, -24, 4, -17, 27, 36, 30, 28, 32, 28,
	33, 40, -16, -16, 40, 20, 27, -16, -23, -16,
	-5, -5, -16, 10, 10, 17, 40, -5, 10,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 0, 0, 0, 5, 0, 6,
	7, 0, 0, 0, 8, 10, 0, 0, 0, 0,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	0, 0, 23, 0, 0, 0, 0, 4, 0, 0,
	28, 0, 30, 24, 34, 36, 37, 38, 39, 0,
	42, 43, 44, 0, 47, 51, 0, 31, 0, 0,
	0, 0, 47, 0, 0, 0, 0, 0, 48, 49,
	0, 52, 53, 0, 0, 0, 0, 0, 0, 9,
	21, 0, 29, 35, 40, 41, 45, 0, 46, 0,
	0, 10, 32, 33, 10, 0, 22, 50, 54, 55,
	0, 0, 0, 25, 26, 0, 10, 0, 27,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:72
		{
			parsedResult = []Procedure{}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:73
		{
			yyVAL.procs = append(yyDollar[1].procs, yyDollar[2].proc)
			parsedResult = yyVAL.procs
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:74
		{
			yyVAL.procs = yyDollar[1].procs
		}
	case 4:
		yyDollar = yyS[yypt-11 : yypt+1]
//line neuroscript.y:77
		{
			var proc Procedure
			proc.Name = yyDollar[3].str
			proc.Params = yyDollar[5].params
			// TODO: Parse docstring $8
			proc.Steps = yyDollar[9].steps
			yyVAL.proc = proc
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:83
		{
			yyVAL.params = []string{}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:83
		{
			yyVAL.params = yyDollar[1].params
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:84
		{
			yyVAL.params = []string{yyDollar[1].str}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:84
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].str)
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
//line neuroscript.y:86
		{
			yyVAL.str = yyDollar[3].str
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:88
		{
			yyVAL.steps = []Step{}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:89
		{
			if yyDollar[2].step.Type != "" {
				yyVAL.steps = append(yyDollar[1].steps, yyDollar[2].step)
			} else {
				yyVAL.steps = yyDollar[1].steps
			}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:90
		{
			yyVAL.steps = yyDollar[1].steps
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:93
		{
			yyVAL.step = yyDollar[1].step
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:94
		{
			yyVAL.step = yyDollar[1].step
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line neuroscript.y:102
		{
			yyVAL.step = newStep("SET", yyDollar[2].str, "", yyDollar[4].str, nil)
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line neuroscript.y:103
		{
			yyVAL.step = newStep("CALL", yyDollar[2].str, "", nil, yyDollar[4].exprs)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:104
		{
			yyVAL.step = newStep("RETURN", "", "", "", nil)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line neuroscript.y:104
		{
			yyVAL.step = newStep("RETURN", "", "", yyDollar[2].str, nil)
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line neuroscript.y:107
		{
			yyVAL.step = newStep("IF", "", yyDollar[2].str, yyDollar[5].steps, nil)
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
//line neuroscript.y:108
		{
			yyVAL.step = newStep("WHILE", "", yyDollar[2].str, yyDollar[5].steps, nil)
		}
	case 27:
		yyDollar = yyS[yypt-9 : yypt+1]
//line neuroscript.y:109
		{
			yyVAL.step = newStep("FOR", yyDollar[3].str, yyDollar[5].str, yyDollar[8].steps, nil)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:112
		{
			yyVAL.str = yyDollar[1].str
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:112
		{
			yyVAL.str = "TOOL." + yyDollar[3].str
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:112
		{
			yyVAL.str = "LLM"
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:114
		{
			yyVAL.str = yyDollar[1].str
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:114
		{
			yyVAL.str = yyDollar[1].str + "==" + yyDollar[3].str
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:114
		{
			yyVAL.str = yyDollar[1].str + "!=" + yyDollar[3].str
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:115
		{
			yyVAL.str = yyDollar[1].str
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:115
		{
			yyVAL.str = yyDollar[1].str + " + " + yyDollar[3].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:116
		{
			yyVAL.str = yyDollar[1].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:116
		{
			yyVAL.str = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:116
		{
			yyVAL.str = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:116
		{
			yyVAL.str = "__last_call_result"
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:116
		{
			yyVAL.str = "(" + yyDollar[2].str + ")"
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:117
		{
			yyVAL.str = "{{" + yyDollar[2].str + "}}"
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:118
		{
			yyVAL.str = yyDollar[1].str
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:118
		{
			yyVAL.str = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:118
		{
			yyVAL.str = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:121
		{
			yyVAL.str = "[" + strings.Join(yyDollar[2].exprs, ", ") + "]"
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:122
		{
			yyVAL.str = "{" + strings.Join(yyDollar[2].mapEntries, ", ") + "}"
		}
	case 47:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:124
		{
			yyVAL.exprs = []string{}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:124
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:125
		{
			yyVAL.exprs = []string{yyDollar[1].str}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:125
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].str)
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
//line neuroscript.y:127
		{
			yyVAL.mapEntries = []string{}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:127
		{
			yyVAL.mapEntries = yyDollar[1].mapEntries
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line neuroscript.y:128
		{
			yyVAL.mapEntries = []string{yyDollar[1].str}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:128
		{
			yyVAL.mapEntries = append(yyDollar[1].mapEntries, yyDollar[3].str)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line neuroscript.y:129
		{
			yyVAL.str = yyDollar[1].str + ":" + yyDollar[3].str
		}
	}
	goto yystack /* stack new state and value */
}
